Grid Simplified
jeetbhalani15/Component-Library pull request #10
Opened 2022-02-22 06:24 UTC by jeetbhalani15

![image](https://user-images.githubusercontent.com/69383785/155074723-fa823d57-6076-4efd-989f-b9dfb3dd7a80.png)

2022-02-22 06:35 UTC, Prabhav-Sharma commented on components/Grid Simplified/grid.css
> +    /* justify-content: center; */
Remove comment

2022-02-22 06:36 UTC, aamrapaliwandhre approved these changes
other than small suggested changes code looks fine to me....

2022-02-22 06:36 UTC, aamrapaliwandhre commented on components/Grid Simplified/grid.css
> +    /* justify-content: center; */
remove this comment

2022-02-22 06:36 UTC, aamrapaliwandhre commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
alt is empty...give it name...

2022-02-22 06:36 UTC, aamrapaliwandhre commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
don't leave alt empty...

2022-02-22 06:36 UTC, iamharnad requested changes
fill the alt attribute for the image tag. its for better coding practise. Otherwise everything is good

2022-02-22 06:36 UTC, iamharnad commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
fill the alt attribute for the image tag. its for better coding practise

2022-02-22 06:36 UTC, iamharnad commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
Here too

2022-02-22 06:36 UTC, iamharnad commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
Here as well

2022-02-22 06:38 UTC, jeetbhalani15 commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
done

2022-02-22 06:38 UTC, jeetbhalani15 commented on components/Grid Simplified/grid.css
> +    /* justify-content: center; */
sure

2022-02-22 06:38 UTC, mehulsatardekar approved these changes
@jeetbhalani15 good to merge the branch with the changes

2022-02-22 06:38 UTC, mehulsatardekar commented on components/Grid Simplified/grid.css
> +    border: 4px solid #6b6a6a;
@jeetbhalani15 I see that this color is being used repeatedly so use var for that

2022-02-22 06:38 UTC, mehulsatardekar commented on components/Grid Simplified/grid.html
> +                    <img src="/images/landging -page 5.png" alt="">
you have empty alt tag inside img tag so provide some text to it

2022-02-22 06:40 UTC, merged

2022-02-23 03:35 UTC, shivamsoni00 reviewed
good look to merge