Text utilities & lists
jeetbhalani15/Component-Library pull request #5
Opened 2022-02-06 09:17 UTC by jeetbhalani15

![image](https://user-images.githubusercontent.com/69383785/152674548-a26eb574-0baf-4305-a5f6-74bd004fb180.png)

2022-02-10 10:55 UTC, rohanmathur91 commented on components/Badges/badges.css
> +    justify-content: center;
You can have a utility class for flex

2022-02-10 10:56 UTC, rohanmathur91 commented on components/Badges/badges.css
> +}
use rem instead of px

2022-02-10 10:56 UTC, rohanmathur91 commented on components/Buttons/button.css
> +    width: 112px;
Same as above, use rem

2022-02-10 10:57 UTC, rohanmathur91 commented on components/Buttons/button.css
> +    height: 44px;
Same as above

2022-02-10 10:57 UTC, rohanmathur91 commented on components/Buttons/button.css
> +    width: 26px;
same as above

2022-02-10 10:57 UTC, rohanmathur91 commented on components/Input/input.css
> +}
Use color variable for this

2022-02-10 10:59 UTC, rohanmathur91 requested changes
In a lot of places you have used px, so try to use rem.

2022-02-10 11:09 UTC, surbhi84 approved these changes
looks good to me.

2022-02-10 11:09 UTC, surbhi84 commented on components/Lists/list.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
suggestion: you can add author and description meta tags as well.

2022-02-10 11:09 UTC, surbhi84 commented on components/Text Utilities/text.html
> +
why headings ?

2022-02-13 12:52 UTC, Jay-Gadhiya approved these changes

2022-02-13 13:33 UTC, merged