Dialogs & modals
jeetbhalani15/Component-Library pull request #6
Opened 2022-02-06 10:05 UTC by jeetbhalani15

![image](https://user-images.githubusercontent.com/69383785/152675954-a4d6512a-4806-4492-bd8a-7f20567636ea.png)

2022-02-10 13:05 UTC, rohanmathur91 commented on .vscode/settings.json
> +}
you can delete this file or can put in .gitignore

2022-02-10 13:12 UTC, rohanmathur91 commented on components/Badges/badges.css
> +}
you can use rem here.

2022-02-10 13:12 UTC, rohanmathur91 commented on components/Badges/badges.css
> +    width: 25px;
use rem wherever possible

2022-02-10 13:14 UTC, rohanmathur91 commented on components/Buttons/button.css
> +    width: 112px;
same as above.

2022-02-10 13:14 UTC, rohanmathur91 commented on components/Buttons/button.css
> +    height: 44px;
same as above.

2022-02-10 13:15 UTC, rohanmathur91 commented on components/Buttons/button.css
> +}
have a variable for this color and use that.

2022-02-10 13:15 UTC, rohanmathur91 commented on components/Dialogs/dailog.css
> +    background-color: rgb(255, 255, 255);
same as above, use variable

2022-02-10 13:17 UTC, rohanmathur91 requested changes
Use rem where value is more than 10px and have variable for all your colors and use that.

2022-02-13 12:51 UTC, Jay-Gadhiya approved these changes

2022-02-13 12:59 UTC, gopalbbharadva approved these changes
Improvement : use relative units instead of absolute unit. (like use rems instead of px). remove unused comments.

2022-02-13 13:34 UTC, merged